### ISSUE TITLE
Protobuf Spec Needs Updating

### ISSUE THREAD

**Issue by wck0** [canonical/landscape-hostagent-api#13]
We need a boolean field for the `InstanceInfo` message to indicate whether or not the instance is the default one.

https://github.com/canonical/landscape-hostagent-api/blob/cd77c9c81c2da9e3d2b04df37bc69cc9ec87681c/hostagent.proto#L23C1-L29C2

UP4W should include this value for each instance when sending the `Connect` command.

**Comment by EduardGomezEscandell** [comment]
Since only one of them can be default, would it be better to have a defaultDistro string (or int?) at the `HostAgentInfo` level? This avoids the problem of more than one being labeled as default.

**Comment by didrocks** [comment]
I agree with @EduardGomezEscandell  to rather have a `defaultDistro` string:
- This avoids having Landscape server to check for each instance that only one is set as the default for data integrity
- The check for Landscape sounds easy: for each distro displayed, only check if it’s the current distro with the distroname (its ID) matches.
- This is a WSL global argument (see below reasons on default distro not registered yet), at the WSL level. We would keep the parity with the WSL concept there.

Also, I suggest it to be a string and not an int:
- The default distro could be a distro that is not managed by landscape (an ubuntu WSL instance with a Landscape client not yet registered, an ubuntu WSL instance with no Landscape client at all is not a managed one or an Ubuntu/non Ubuntu distro we know care about (no Pro service installed). If this was an int, what would we return? -1? Sounds like less logical
- And finally, an int will force both side to ensure we respect the order of the list of distros.

Does this make sense?

**Comment by wck0** [comment]
A string at the `HostagentInfo` level would work just as well.

To my mind, Landscape only needs to correctly reflect the information it receives from UP4W, so validation is not crucial.
